name: hub-mirror-by-multiple

on:
  issues:
    types:
      - opened

permissions:
  issues: write
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      QYWX_ROBOT_URL: "${{ secrets.QYWX_ROBOT_URL }}"
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: "${{ secrets.DOCKER_XXX_TOKEN }}"

      - name: Print image info to comment
        id: print-image-info
        env:
          GH_TOKEN: "${{ github.token }}"
          TITLE: "${{ github.event.issue.title }}"
          BODY: "${{ github.event.issue.body }}"
        run: |
          # 提取目标仓库地址、名称空间、架构
          TARGET_REGISTRY=$(echo "$TITLE" | awk -F ']:|\\[' '{print $2}' | tr -d ' ')
          TARGET_REPOSITORY=$(echo "$TITLE" | awk -F ']:|\\[' '{print $4}' | tr -d ' ')
          TARGET_ARCH=$(echo "$TITLE" | awk -F ']:|\\[' '{print $6}' | tr -d ' ')
          
          echo "仓库地址：${TARGET_REGISTRY}"
          echo "仓库名称空间：${TARGET_REPOSITORY}"
          echo "架构：${TARGET_ARCH}"
          
          # 提取镜像列表
          reg_exp="^[a-zA-Z0-9/:\.\-]+$"
          echo "####需要同步的镜像清单" > "image.txt"
          IFS=$'\n'
          for item in $(echo "$BODY" | grep -Eo '[a-zA-Z0-9/:\.\-]+'); do
            if [[ "$item" =~ $reg_exp ]]; then
              echo "$item" >> "image.txt"
            fi
          done
          
          # 从 image.txt 中提取第一个镜像的名称和版本
          if [[ $(cat image.txt | wc -l) -gt 0 ]]; then
            IMAGE_LINE=$(head -n 1 image.txt)
            IFS=':' read -r IMAGE_NAME IMAGE_VERSION <<< "$IMAGE_LINE"
            NEW_NAME=${IMAGE_NAME##*/}
            echo "image_name=${IMAGE_NAME}" >> "${GITHUB_OUTPUT}"
            echo "image_version=${IMAGE_VERSION}" >> "${GITHUB_OUTPUT}"
            echo "new_name=${NEW_NAME}" >> "${GITHUB_OUTPUT}"
          else
            echo "没有有效的镜像名称"
            exit 1
          fi
          
          echo "target_registry=${TARGET_REGISTRY}" >> "${GITHUB_OUTPUT}"
          echo "target_repository=${TARGET_REPOSITORY}" >> "${GITHUB_OUTPUT}"
          echo "target_arch=${TARGET_ARCH}" >> "${GITHUB_OUTPUT}"
          
          # 发送评论
          gh issue comment "${{ github.event.issue.html_url }}" -b "$(echo -e "\n镜像仓库：${TARGET_REGISTRY}\n仓库名称空间：${TARGET_REPOSITORY}\n架构：${TARGET_ARCH}\n$(cat image.txt)\n")"
          gh issue comment "${{ github.event.issue.html_url }}" -b "镜像 ${IMAGE_NAME} 同步中...[详情请查看](https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }})"

      - name: Login to Docker Registry
        env:
          TARGET_REGISTRY: "${{ steps.print-image-info.outputs.target_registry }}"
          DOCKER_USERNAME: "${{ secrets.DOCKER_USERNAME }}"
          DOCKER_PASSWORD: "${{ secrets.DOCKER_PASSWORD }}"
        run: |
          docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD" "$TARGET_REGISTRY"

      - name: Pull, tag, and push Docker image
        env:
          IMAGE_NAME: "${{ steps.print-image-info.outputs.image_name }}"
          IMAGE_VERSION: "${{ steps.print-image-info.outputs.image_version }}"
          NEW_NAME: "${{ steps.print-image-info.outputs.new_name }}"
          TARGET_REGISTRY: "${{ steps.print-image-info.outputs.target_registry }}"
          TARGET_REPOSITORY: "${{ steps.print-image-info.outputs.target_repository }}"
          TARGET_ARCH: "${{ steps.print-image-info.outputs.target_arch }}"
        run: |
          if [ -n "$TARGET_ARCH" ]; then
            docker pull --platform "$TARGET_ARCH" "$IMAGE_NAME:$IMAGE_VERSION"
          else
            docker pull "$IMAGE_NAME:$IMAGE_VERSION"
          fi
          docker tag "$IMAGE_NAME:$IMAGE_VERSION" "$TARGET_REGISTRY/$TARGET_REPOSITORY/$NEW_NAME:$IMAGE_VERSION"
          docker push "$TARGET_REGISTRY/$TARGET_REPOSITORY/$NEW_NAME:$IMAGE_VERSION"

      - name: qyweixin send message
        if: ${{ env.QYWX_ROBOT_URL != '' }}
        uses: chf007/action-wechat-work@master
        env:
          WECHAT_WORK_BOT_WEBHOOK: "${{ secrets.QYWX_ROBOT_URL }}"
          IMAGE_URL: "${{ steps.print-image-info.outputs.target_registry }}/${{ steps.print-image-info.outputs.target_repository }}/${{ steps.print-image-info.outputs.new_name }}:${{ steps.print-image-info.outputs.image_version }}"
        with:
          msgtype: markdown
          content: |
            # 镜像同步成功
        ${IMAGE_URL}
        ```

  - name: Close issue
    env:
      GH_TOKEN: "${{ github.token }}"
      TARGET_REGISTRY: "${{ steps.print-image-info.outputs.target_registry }}"
      TARGET_REPOSITORY: "${{ steps.print-image-info.outputs.target_repository }}"
      NEW_NAME: "${{ steps.print-image-info.outputs.new_name }}"
      IMAGE_VERSION: "${{ steps.print-image-info.outputs.image_version }}"
    run: |
      gh issue comment "${{ github.event.issue.html_url }}" -b "$(echo -e "镜像同步完成 ${NEW_NAME} ，新的镜像 ${TARGET_REGISTRY}/${TARGET_REPOSITORY}/${NEW_NAME}:${IMAGE_VERSION}\n\n快速拉取命令，Docker客户端\n\`\`\`sh\ndocker image pull ${TARGET_REGISTRY}/${TARGET_REPOSITORY}/${NEW_NAME}:${IMAGE_VERSION}\n\`\`\`\n\nContainerd客户端拉取命令\n\`\`\`sh\nctr -n k8s.io image pull ${TARGET_REGISTRY}/${TARGET_REPOSITORY}/${NEW_NAME}:${IMAGE_VERSION}\n\`\`\`\n")"
      gh issue edit "${{ github.event.issue.html_url }}" --add-label "succeeded" -b "IMAGE SYNC"
      gh issue close "${{ github.event.issue.html_url }}" --reason "completed"

  - name: Failed Sync and Close issue
    if: failure()
    env:
      GH_TOKEN: "${{ github.token }}"
      IMAGE_NAME: "${{ steps.print-image-info.outputs.image_name }}"
      NEW_NAME: "${{ steps.print-image-info.outputs.new_name }}"
      TARGET_REGISTRY: "${{ steps.print-image-info.outputs.target_registry }}"
      TARGET_REPOSITORY: "${{ steps.print-image-info.outputs.target_repository }}"
    run: |
      gh issue comment "${{ github.event.issue.html_url }}" -b "镜像 ${IMAGE_NAME} 同步失败...[详情请查看](https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }})，请检查 image参数，如果还需要同步，请重新提交正确的issue"
      gh issue edit "${{ github.event.issue.html_url }}" --add-label "failure" -b "IMAGE SYNC"
      gh issue close "${{ github.event.issue.html_url }}" --reason "not planned"
